# permissions for end users to edit minecrafts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: minecraft-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - minecrafts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - minecrafts/status
  verbs:
  - get
