apiVersion: cache.example.com/v1alpha1
kind: Minecraft
metadata:
  name: minecraft-sample
spec:
  # TODO(user): edit the following value to ensure the number
  # of Pods/Instances your Operand must have on cluster
  size: 1
